### ISSUE TITLE
Translation stoped working - Need to adapt to new Morfix version

### ISSUE THREAD

**Issue by Yitzchak-Shachar** [eyal0/hebrew-tooltip-translations-for-chrome#3]
Seems https://www.morfix.co.il/ changes look-n-feel and maybe also the api\interface
can you adapt?

**Comment by eyal0** [comment]
Thanks for letting me know.  I will begin.

How long has it broken do you estimate?

**Comment by eyal0** [comment]
This is fixed in https://github.com/eyal0/hebrew-tooltip-translations-for-chrome/commit/f08470585f899a23f930b9d9ff802a64dae2178c

Please upgrade to version 2.8.

**Comment by Yitzchak-Shachar** [comment]
great
works fine now
this was the fastes extension fix i've ever seen
10x
